/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class main_Test */

#ifndef _Included_main_Test
#define _Included_main_Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     main_Test
 * Method:    testJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_main_Test_testJNI (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
